services:
    php:
        build:
            dockerfile: Dockerfile
            context: .
        env_file: .env
        ports:
            - 8080:80
        depends_on:
            - database

    database:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - 33066:3306
        volumes:
            - database:/var/lib/mysql

volumes:
  database:
    driver: local
