#!/command/with-contenv sh

cd /var/www

# Create .env file from environment variables
echo "
APP_ENV=$APP_ENV
APP_DEBUG=$APP_DEBUG
APP_LOG=$APP_LOG
APP_NAME=\"$APP_NAME\"
APP_URL=\"$APP_URL\"
APP_KEY=$APP_KEY
DB_HOST=\"$DB_HOST\"
DB_PORT=$DB_PORT
DB_DATABASE=\"$DB_DATABASE\"
DB_USERNAME=\"$DB_USERNAME\"
DB_PASSWORD=\"$DB_PASSWORD\"
CACHE_DRIVER=$CACHE_DRIVER
SESSION_DRIVER=$SESSION_DRIVER
SESSION_LIFETIME=$SESSION_LIFETIME
QUEUE_DRIVER=$QUEUE_DRIVER
MAIL_DRIVER=$MAIL_DRIVER
MAIL_HOST=\"$MAIL_HOST\"
MAIL_PORT=$MAIL_PORT
MAIL_USERNAME=\"$MAIL_USERNAME\"
MAIL_NAME=\"$MAIL_NAME\"
MAIL_PASSWORD=\"$MAIL_PASSWORD\"
MAIL_ENCRYPTION=$MAIL_ENCRYPTION
MAIL_FROM_ADDRESS=\"$MAIL_FROM_ADDRESS\"
CMS_BACKEND_FORCE_SECURE=$CMS_BACKEND_FORCE_SECURE
CMS_ASSET_DEEP_HASHING=$CMS_ASSET_DEEP_HASHING
CMS_EDGE_UPDATES=$CMS_EDGE_UPDATES
CMS_ASSET_MINIFY=$CMS_ASSET_MINIFY
CMS_BACKEND_URI=\"$CMS_BACKEND_URI\"
CMS_BACKEND_FORCE_REMEMBER=$CMS_BACKEND_FORCE_REMEMBER
CMS_CONVERT_LINE_ENDINGS=$CMS_CONVERT_LINE_ENDINGS
CMS_ACTIVE_THEME=\"$CMS_ACTIVE_THEME\"
CMS_ROUTES_CACHE=$CMS_ROUTES_CACHE
CMS_ASSET_CACHE=$CMS_ASSET_CACHE
CMS_LINK_POLICY=$CMS_LINK_POLICY
CMS_ENABLE_CSRF=$CMS_ENABLE_CSRF
APP_LOCALE=$APP_LOCALE
APP_FALLBACK_LOCALE=$APP_FALLBACK_LOCALE
" >.env

php artisan config:cache

php artisan october:mirror public --relative
php artisan october:up

# Remove the media folder public link if exists
rm -f ./public/storage/app/media

# Create the media folder public link
ln -s ../../../storage/app/media ./public/storage/app/media

# Change public folder ownership
chown -R www-data:www-data /var/www
